# Generated by Django 3.1.6 on 2021-02-21 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sokrat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки'},
        ),
    ]
